language: node_js
node_js:
  - stable

install:
  - npm install -g codecov
  - npm install

branches:
  only:
    - master
    - dev

script:
  - npm run lint
  - npm test
  - npm run report-coverage
  - codecov